### ISSUE TITLE
Looks like its missing a declaration of 'classes'

### ISSUE THREAD

**Issue by justincrosbie** [moff/angular2-flash-messages#16]
ERROR in /Users/[myprojectpath]/src/$$_gendir/node_modules/angular2-flash-messages/module/flash-messages.component.ngfactory.ts (211,87): Property 'classes' does not exist on type 'FlashMessagesComponent'.

If I add this it all works. Occurs in 1.0.5

**Comment by manojkumarbehera** [comment]
Not getting the solution, what need to add.
As I am also getting same issue on prod build - `(ng build --prod) `and getting this error.

```
ERROR in D:/<project path>/src/$$_gendir/node_modules/angular2-flash-messages/module/flash-messages.component.ngfactory.ts (1,1): 
Property 'classes' does not exist on type 'FlashMessagesComponent'.
```

**Comment by ashishbhagasra** [comment]
Thanks Justin,

Find the FlashMessagesComponent under node-modules->angular2-flash-messages->module->flash-messages.component.ts.

Just add a property names as 'classes' in FlashMessagesComponent and build again.

**Comment by moff** [comment]
Hi, @justincrosbie !
I've updated the package - please check it out and let me know. Thanks for the feedback!

**Comment by justincrosbie** [comment]
Hi Paul,

I just checked it out, all seems to be working fine now, thanks for the
fast response :)

Cheers,
Justin

**Comment by moff** [comment]
You're welcome, @justincrosbie !
