### ISSUE TITLE
prod build failing

### ISSUE THREAD

**Issue by manojkumarbehera** [moff/angular2-flash-messages#17]
http://stackoverflow.com/questions/43084301/angular2-flash-messages-prod-build-failing?noredirect=1#comment73252396_43084301

**Comment by moff** [comment]
Hi, @manojkumarbehera !
I've updated the package - please check it out and let me know. Thanks for the feedback!

**Comment by manojkumarbehera** [comment]
Hi Moff
Now using 1.0.7 but getting this error
ERROR in FlashMessagesModule is not an NgModule

**Comment by moff** [comment]
@manojkumarbehera I've just tested latest package version(1.0.8) with Angular CLI and it works fine.
Let me know, if you still experience this issue.

**Comment by manojkumarbehera** [comment]
Thanks Moff, I will use 1.0.8

**Comment by moff** [comment]
@manojkumarbehera please let me know if it works good now and I'll close this issue.

**Comment by manojkumarbehera** [comment]
Yup, 1.0.8 working fine.Thanks
