### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by GhAbd** [moff/angular2-flash-messages#19]
when I run `ng build` I got :
       

> ERROR in FlashMessagesModule is not an NgModule

When I run `ng serve` the same error appears just once and then everything work. But now it can't build! 
Any possible solution?﻿

**Comment by Divam** [comment]
I am getting the same error. Were you able to find a work around?

**Comment by vasilis-exo** [comment]
I have the same issue. Please you must find a solution because I cant work my project. The problem appeared when I update Angular version, Angular-Cli and Typescript.

**Comment by moff** [comment]
@vasilis-exo, @Divam, @GhAbd I've just tested latest package version with Angular CLI and it works fine.
Let me know, if you still experience this issue.

**Comment by vasilis-exo** [comment]
@moff I update your package to latest version and everything seems to be working fine! Thanks
