### ISSUE TITLE
angular2-flash-messages

### ISSUE THREAD

**Issue by seanrenton** [moff/angular2-flash-messages#20]
Continually have to copy and past in new node modules because angular2-flash-messages cant be found in my node_modules. This is very annoying as it does it when I haven't even brought any new software in and continues to slow my progress. The error reads.

Error: cannot find FlashMessagesModule in app.module.ts and one of my own components even though I've clearly imported it in and have made sure to save as a dependency.

**Comment by tariq-mahmood-nxb** [comment]
index.d.ts is missing in new installs, just create the file and add
export * from './module/index';

**Comment by seanrenton** [comment]
Awesome thank you for the fast response tariq!

**Comment by moff** [comment]
Hello, @seanrenton , I've updated the package - install new version and let me know how it goes now.
Check SystemJS config guide in readme.md, if you use it.
