### ISSUE TITLE
angular 2 flash messages show multiple times

### ISSUE THREAD

**Issue by zap-deepak** [moff/angular2-flash-messages#22]
Sir if we call show message two times it should override old one.
But it shows both flash message.
Which looks so bad.

**Comment by moff** [comment]
@zap-deepak hello! Actually this is not a bug, but a feature - it was implemented this way intentionally.
I think I'll add an additional parameter to .show() method to show only one message - the latest one.
Thank you for a feedback!

**Comment by zap-deepak** [comment]
@moff Thanks for your feedback. 
But for now i have used a trick to achieve my goal, i hope it will help to others also.

#flashMessages .flash-message{display:none;}
#flashMessages .flash-message:last-child{display:block;}

**Comment by chamrith** [comment]
dyydyuu

**Comment by mohit6481** [comment]
Hi Sir.. did you add any parameter to show() method to show only one message? or I have to add css to achieve this.
