### ISSUE TITLE
Rollup.js Config for Ionic

### ISSUE THREAD

**Issue by jorgeitenjr** [moff/angular2-flash-messages#3]
Hi @moff 
I am trying to use your lib in a Ionic 2 app. But I got the this issue: https://github.com/driftyco/ionic-app-scripts/issues/68 related to rollup.js config. Do you plan to release any updates regarding to  that update?

**Comment by moff** [comment]
Hi @jorgeitenjr!

Please post here error message you receive. Thank you!

**Comment by moff** [comment]
@jorgeitenjr by the way, I wonder if it will work this way:

import { FlashMessagesModule } from 'angular2-flash-messages/module';

**Comment by jorgeitenjr** [comment]
Hello @moff,
Indeed, I did not find the guide too.
The error message is:
`Error: Module node_modules/angular2-flash-messages/index.js does not export FlashMessagesService (imported by /home/projects/project/src/pages/login/login.ts)
    at Module.trace (node_modules/rollup/dist/rollup.js:7706:29)
`
