### ISSUE TITLE
Latest release introduces breaking change on revision

### ISSUE THREAD

**Issue by wysawyg** [moff/angular2-flash-messages#30]
I had npm set to ^1.0.5 and the latest revision broke our code because we were still using an import of FlashMessagesModule, not FlashMessagesModule.forRoot() in the app.module.ts.

**Comment by moff** [comment]
@wysawyg yes, there is a breaking change, sorry about that! I mentioned that in README.md
It's because of this pull request I merged https://github.com/moff/angular2-flash-messages/pull/12
It now supports lazy loading.

**Comment by moff** [comment]
@wysawyg I've just unpublished new version that broke your code and published 2.0.0
So I hope not many other people will face this problem as well.
Thank you for your feedback!
