### ISSUE TITLE
Cannot find module 'angular2-flash-messages';

### ISSUE THREAD

**Issue by clevadani** [moff/angular2-flash-messages#33]
I keep getting this error. And I've tried all possible suggestions and they've all failed. Any ideas?

**Comment by websystemsoftware** [comment]
i have the same problem
any idea??

**Comment by moff** [comment]
@clevadani , @websystemsoftware I've just pushed new version of the package to NPM - update and let me know if it works properly. Thanks!

**Comment by c0d3x** [comment]
/node_modules/angular2-flash-messages/module/module"' has no exported member 'FlashMessagesService'.

**Comment by moff** [comment]
@c0d3x update the package and let me know
