### ISSUE TITLE
UNMET PEER DEPENDENCY on Angular 5.1.1

### ISSUE THREAD

**Issue by mikebrsv** [moff/angular2-flash-messages#36]
Getting 
```
+-- UNMET PEER DEPENDENCY @angular/compiler@5.1.1
+-- UNMET PEER DEPENDENCY @angular/core@5.1.1
+-- UNMET PEER DEPENDENCY @angular/http@5.1.1
```
and `_this._flashMessagesService.show is not a function` on Angular 5.1.1.

**Comment by mikebrsv** [comment]
> and `_this._flashMessagesService.show is not a function` on Angular 5.1.1.
It was my bad. Forgot to include `<flash-messages></flash-messages>`.

Unmet dependencies are still an issue.

**Comment by moff** [comment]
@mikebrsv I've just published updated package so it should be fixed by now. Let me know if it works properly. Thanks for the feedback!

**Comment by mikebrsv** [comment]
@moff Oops, forgot to close the issue. Thank, everything works fine now!
